apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{tag '  .Chart.Name '}}-deployment"
  labels:
    chart: '{{tag ' .Chart.Name '}}-{{{tag ' .Chart.Version | replace "+" "_" '}}}'
spec:
  replicas: {{tag ' .Values.replicaCount '}}
  revisionHistoryLimit: {{tag ' .Values.revisionHistoryLimit '}}
  template:
    metadata:
      labels:
        app: "{{tag '  .Chart.Name '}}-selector"
        version: "current"
    spec:
      containers:
      - name: "{{tag '  .Chart.Name  '}}"
        image: "{{tag ' .Values.image.repository '}}:{{tag ' .Values.image.tag '}}"
        imagePullPolicy: {{tag ' .Values.image.pullPolicy '}}
{{#has language 'java'}}
{{tag ' if .Values.istio.enabled '}}
{{tag ' else '}}
{{/has}}
        readinessProbe:
          httpGet:
          {{! healthEndpoint is configured in the index.js and is different for basicweb}}
          {{#has language 'java'}}
            path: /{{applicationName}}/{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 9080
          {{/has}}
          {{#has language 'spring'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 8080
          {{/has}}
          initialDelaySeconds: 20
{{#has language 'java'}}
{{tag ' end '}}
{{/has}}
        resources:
          requests:
            cpu: "{{tag ' .Values.image.resources.requests.cpu '}}"
            memory: "{{tag ' .Values.image.resources.requests.memory '}}"
        env:
          - name: PORT
            value: "{{tag ' .Values.service.servicePort '}}"
          {{#each storageDeploys.env}}
          - name: {{@key}}
            value: {{{this}}}
          {{/each}}
          - name: APPLICATION_NAME
            value: "{{tag ' .Release.Name '}}"
          - name: APM_BM_GATEWAY_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: apm_bm_gateway_url
                optional: true
          - name: APM_KEYFILE
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: apm_keyfile
                optional: true
          - name: APM_KEYFILE_PSWD
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: apm_keyfile_pswd
                optional: true
          - name: IBAM_INGRESS_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibam_ingress_url
                optional: true
          - name: IBAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibam_token
                optional: true
