- name: IBM_APM_SERVER_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_server_url
      optional: true
- name: IBM_APM_KEYFILE
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile
      optional: true
- name: IBM_APM_KEYFILE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile_password
      optional: true
- name: IBM_APM_INGRESS_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_ingress_url
      optional: true
- name: IBM_APM_ACCESS_TOKEN
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_access_token
      optional: true
{{#each storageDeploys.env}}
- name: {{@key}}
  value: {{{this}}}
  optional: true
{{/each}}