apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    chart: "{{tag ' .Chart.Name'}}-{{tag ' .Chart.Version'}}"
    heritage: "{{tag ' .Release.Service'}}"
    release: "{{tag ' .Release.Name'}}"
    app: "{{tag ' .Chart.Name'}}-selector"
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:{{servicePorts.prometheus}}']
      - job_name: "{{tag ' .Chart.Name'}}-selector"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "{{tag ' .Chart.Name'}}-selector"
            action: keep
